### ISSUE TITLE
customize circle button

### ISSUE THREAD

**Issue by zaidq** [paper-leaf/alton#10]
i am still newbie in web design, can you please tell me how to modifiy the circle button?? (useSlideNumbers)
.i want to make it customize like at the header or footer
thanks for your attention

**Comment by paper-leaf** [comment]
Hey Zaidq, 

You have two options for customizing the circle buttons. These are the border color of the button, and the inside of the circle. When it is an active slide, the circle will be a solid circle, the color of the slideNumbersBorderColor. 

The ones we use are: 
slideNumbersBorderColor: '#fff',
slideNumbersColor: 'transparent',

Everything else including animations, position, size etc, is handled by the plugin.

Let me know if you have any other questions on how we accomplished what's on the demo site.

**Comment by zaidq** [comment]
thanks for ur answer.. but still i really want to make it another way..
maybe a custom button, what is posible to call another slide with custom button??

**Comment by paper-leaf** [comment]
There is nothing built in to Alton at the moment that can do what you are requesting.

If you are trying to customize the look of the buttons beyond what is supported in the plugin itself, you'll have to use the classes and id's they have been assigned, and style them using CSS: 

#slide-numbers for the container
.paginate for each individual button.

At this is time this is the only support we have for any customization for the buttons, but we are always looking to add new features and options for this kind of thing.

**Comment by zaidq** [comment]
thanks.. i look forward your next release.
