### ISSUE TITLE
Changing useSlideNumbers to false causes error

### ISSUE THREAD

**Issue by con322** [paper-leaf/alton#12]
I have set the useSlideNumbers to false and get the following error in my console:

```
Uncaught TypeError: Cannot read property '2' of undefined
```

Which relates to the following lines in the script  within the slideindex function within the else brackets (line 250 of the un minified version)

```
$(slideNumbers[$(element).parent().children().index(element)]).toggleClass('active');
```

My options are as follows

```
$(document).alton({
    fullSlideContainer: 'full', // Tell Alton the full height container
    singleSlideClass: 'slide', // Tell Alton the full height slide class
    useSlideNumbers: false, // Set to false if you don't want to use pagination
    slideNumbersBorderColor: '#fff', // Set the outside color of the pagination items
    slideNumbersColor: 'transparent', // Set the inner color of the pagination items
    bodyContainer: 'pageWrapper', // Tell Alton the body class
});
```

**Comment by ntan97** [comment]
Hey Con322, 

Thanks for the detailed report, I'll be looking closely into this, and will update this thread as soon as I have a bug fix for you, or if I need any further information.

**Comment by con322** [comment]
Hey Just wondering if you have had chance to investigate this error/bug?

**Comment by paper-leaf** [comment]
Hey Con322, 

Sorry for the delay here, we were working on a big stability fix for the plugin, and I lumped this fix in there. 

This should be now resolved, and I highly encourage you to download the latest version 1.1.0, 

You can see 46bb1c9bd912ab59bcc610f9f20ec268925050bf for the full commit details.
