### ISSUE TITLE
Can I remove the function of scrolling by number keys on keyboard?

### ISSUE THREAD

**Issue by ghost** [paper-leaf/alton#13]
I recently discovered this plugin that I wanted to try designing a login page for learning purposes. With reference to your bookend demo, I plan to use the header as a login page and the footer part as a sign up part, where each section consists of a form with some basic inputs for a user registration page to find out that pressing 1 and 2 would lead me to either the top or bottom of the page that I would find it an issue when the input required for the page that I'm designing to consist of numbers that may consist of 1 or 2.  I wonder if it would be possible to remove the function, or may I know how I could remove the function in my own? I'm sorry for my poorly-written description of request.

**Comment by paper-leaf** [comment]
Unfortunately this is something we built in to try to cover all accessibility cases where the site could be navigated with the keyboard. 

If you would like to remove this functionality, I would encourage you to take a look at line 574 of the uncompressed file and remove the following code. 

``` javascript
// Key Up Key Down etc
                $(document).keydown(function (e) {
                    switch (e.which) {
                    case 40: // arrowUp
                        $(document).moveDown(e);
                        e.preventDefault();
                        break;
                    case 32: // pageUp 
                        $(document).moveDown(e);
                        e.preventDefault();
                        break;
                    case 33: // pageUp 
                        $(document).moveDown(e);
                        e.preventDefault();
                        break;
                    case 34: // pageUp
                        $(document).moveUp(e);
                        e.preventDefault();
                        break;
                    case 38: // arrowDown
                        $(document).moveUp(e);
                        e.preventDefault();
                        break;
                    case 50: // home
                        $(document).scrollTo('.' + settings.firstClass);
                        e.preventDefault();
                        break;
                    case 49: // end
                        $(document).scrollTo(last);
                        e.preventDefault();
                        break;
                    }
                });
            }
```

This is an unofficial fix to the problem you are having, and if you have any further problems after modifying the plugin I am afraid we won't be able to help you out, as it's outside the use cases this plugin was designed for.

**Comment by paper-leaf** [comment]
@YuhJing0922 I believe I misunderstood your request.

Looks like this may be a bug on our end. I've updated the reqeust as such and we'll be looking into what's going on here.

Sorry for the confusion.

**Comment by ghost** [comment]
It's alright, no worries! And thank you for looking into the issue.

**Comment by ntan97** [comment]
@YuhJing0922 Sorry for the delay on this, I've just pushed an update to this morning that should resolve any issues you were having. Let me know if there are any other issues.

For more info see: f6fcc7d16c3ebfc981a716368ce4dec501efa559
