### ISSUE TITLE
Space bar for scrolling breaks

### ISSUE THREAD

**Issue by trexchard** [paper-leaf/alton#14]
I noticed on the bookends example that there is an error when I'm spacing through slides. If get to the bottom and hit "Page Up" to get to the top that it breaks the space bar scrolling.

Thanks! This is a great tool.

**Comment by ntan97** [comment]
Thanks so much for reporting this.

I'll be looking into this as soon as we get a chance to push up a few updates here.

**Comment by ntan97** [comment]
We've now adjusted the way that the Home and End buttons scroll here, and this issue should now be resolved in the latest commit. 

Please let us know if you have any future issues.
