### ISSUE TITLE
Thoughts on alton on mobile/tablet devices 

### ISSUE THREAD

**Issue by con322** [paper-leaf/alton#16]
Awesome plugin, this enhancement may be for another plugin but it would be cool to know your thoughts anyway.

So on mobile the height of each slide is still equal to the height of the viewport however if the content of the slide takes up more space that the slide on mobile it extend out of the element, get hidden or just looks really squished.

I was wondering how can this plugin still be used/improved for mobile, for example maybe making the slides min-height the viewport height instead of giving it a fixed height? Not to sure what else you could do to improve the functionality for mobile devices

**Comment by ntan97** [comment]
Hey Con322, 

I think you're on to something here. I think you were trying to mention this before and I completely didn't understand so I apologize for that. I'm hoping to sit down within the next few weeks and address many of the new bugs that have popped here. 

Appreciate your help in this, and I'll update this thread with progress/any other ideas.

**Comment by ntan97** [comment]
@con322 we've updated Alton in the latest commit to handle mobile and tablet layouts better based on your feedback. Thanks again for you help and patience as we figured this out. 

771ed4d57f1588c3eb92e23c5891db24703ca53f
