### ISSUE TITLE
Callback?

### ISSUE THREAD

**Issue by theones** [paper-leaf/alton#24]
Hello can we get some callback for function to stop function working (when we use lightbox or fancybox) and after close fancybox start alton again? It's easy to do with fancybox (we got some callbacks on close and open, but how to stop function from website).

**Comment by ntan97** [comment]
hey @theones I'm assuming you're just talking about pausing the event listener for the scroll, and key presses?

In the use case above, I'm assuming a user will click on a photo, the modal or lightbox will pop up, and the user will be able to interact with the content as per normal? I just want to make sure I fully understand the use case here.
