### ISSUE TITLE
Pressing Down Arrow causes page to scroll all the way back to top

### ISSUE THREAD

**Issue by TannerHolm** [paper-leaf/alton#27]
Alton is probably the best scrolling plugin I've seen yet! However, I'm having one issue, when I hit the down arrow on the keyboard to scrolldown, it immediately scrolls me up to the very top of the page, through all previous sections. Have you seen anything like this before?

**Comment by TannerHolm** [comment]
Nevermind! My styles were jacking things up,  Thanks for all your hard work!

**Comment by ntan97** [comment]
Thanks @TannerHolm for the update and I'm glad to see you got your issue sorted!
