### ISSUE TITLE
Excessive delay on scroll

### ISSUE THREAD

**Issue by paper-leaf** [paper-leaf/alton#5]
On Certain Devices, (Macbooks, devices with inertia scroll etc), delay will not cease until user has full stopped scrolling for .5s. 

Pointed out by a few users on Reddit

**Comment by ntan97** [comment]
Status Update:

We have been working hard on all the feedback we've received.

We currently have a new version undergoing testing at the moment, that should improve scrolling response on all devices. No release date at the moment but it is coming. 

I will update this thread when the update is live.

**Comment by paper-leaf** [comment]
We've implemented a fix for this in the lates 1.1.0 release. Here's a couple notes: 

Basically what happened is that we’re trying to re-enable the scrolling as soon as the user has stopped scrolling. The only problem is that on devices with inertia scroll the events we use to detect this don’t stop. They can’t even be reset, or stopped as it’s an input that is taken care of by the OS. We’ve managed to reduce the delay to the point that you need to be scrolling through them very quickly, without consuming any content in order to trigger this. Though it’s not a perfect solution we feel this is a much needed improvement, that will help everyone create better user experiences.
